### ISSUE TITLE
How to click to detail Activity Wallpaper ?

### ISSUE THREAD

**Issue by helmifluida** [architjn/MaterialIconPackTemplate#1]
Thanks for template :) i hope add feature detail Activity Wallpaper

**Comment by architjn** [comment]
I feel like there is no extra information to show on that activity
So i didn't added that
Any suggestions what should i add in detailed wallpaper activity?

**Comment by helmifluida** [comment]
Add button save image and favorite :) and i hope add menu favorite in navigation drawer, 
thanks architjn for template
