### ISSUE TITLE
OverpendingTransition

### ISSUE THREAD

**Issue by helmifluida** [architjn/MaterialIconPackTemplate#2]
OverPendingTransition on MainActivity not work , not transition, how fix it ??

**Comment by architjn** [comment]
Can you show me your code?

**Comment by Kexagia** [comment]
Archita hello i have an error Error: (1, 1) the problem occurred Evaluating project ': app'.

> Failed to apply plugin [id 'com.android.applicatio's']
>     > Grade version 2.10 is required. Current version is 2.8. If using the grade of the wrapper, try editing the distributionurl in C: \ Users \ Home \ Desktop \ materialıconpacktemplat-master \ grade A \ wrapper \ gradle-wrapper.properties to gradle-2.10-all.zip

**Comment by architjn** [comment]
issue is resolved
